package main

var weatherFontMapping = map[string]string{
	"bkn":      "a",
	"dust":     "d",
	"few":      "e",
	"fg":       "h",
	"fzra":     "i",
	"fzrara":   "l",
	"hi_shwrs": "m",
	"hi_tsra":  "p",
	"ip":       "q",
	"mist":     "t",
	"mix":      "u",
	"nsurtsra": "w",
	"ovc":      "x",
	"ra":       "b",
	"ra1":      "c",
	"raip":     "f",
	"rasn":     "g",
	"nsct":     "j",
	"shra":     "k",
	"skc":      "n",
	"smoke":    "o",
	"sn":       "r",
	"tsra":     "s",
	"wind":     "v",
	"hot":      "n",
}
